name: CI Pipeline

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            
            - name: Install dependencies
              run: |
                pip install -r requirements.txt
                pip install flake8

            - name: Lint
              run: flake8 .

            - name: Log in to Docker Hub
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image with tag
              run: |
                docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-canary-app:${{ github.sha }} .
                docker push ${{ secrets.DOCKERHUB_TOKEN }}/flask-canary-app:${{github.sha}}